// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pege.Data;

#nullable disable

namespace Pege.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260922080307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Pege.Data.StreamInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Stopped")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChannelId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Streams");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StreamInfo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Pege.Data.FileAudioStreamInfo", b =>
                {
                    b.HasBaseType("Pege.Data.StreamInfo");

                    b.Property<string>("Path")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.HasDiscriminator().HasValue("File");
                });

            modelBuilder.Entity("Pege.Data.RelayAudioStreamInfo", b =>
                {
                    b.HasBaseType("Pege.Data.StreamInfo");

                    b.Property<bool?>("MetadataSwap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.HasDiscriminator().HasValue("AudioRelay");
                });
#pragma warning restore 612, 618
        }
    }
}
