//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pege.Resource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pege.Resource.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application launch error:
        ///{0}.
        /// </summary>
        internal static string AppLaunchError {
            get {
                return ResourceManager.GetString("AppLaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio rate reading error for file: {0}. Reason: {1}.
        /// </summary>
        internal static string AudioRateReadingError {
            get {
                return ResourceManager.GetString("AudioRateReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The error occured while handling the bot command {0}. Reason: {1}.
        /// </summary>
        internal static string BotCommandHandlingError {
            get {
                return ResourceManager.GetString("BotCommandHandlingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multipart boundary length exceeded..
        /// </summary>
        internal static string BoundaryLengthExceeded {
            get {
                return ResourceManager.GetString("BoundaryLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Codec name reading error for file: {0}. Reason: {1}.
        /// </summary>
        internal static string CodecNameReadingError {
            get {
                return ResourceManager.GetString("CodecNameReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection lost: {0}. Reconnecting in 10 seconds....
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory containing files does not exist: {0}..
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFmpeg not available..
        /// </summary>
        internal static string FFmpegNotAvailable {
            get {
                return ResourceManager.GetString("FFmpegNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFmpeg not found. Make sure FFmpeg is installed and in PATH..
        /// </summary>
        internal static string FFmpegNotFound {
            get {
                return ResourceManager.GetString("FFmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFmpeg did not create output file.
        ///Input file: {0}.
        /// </summary>
        internal static string FFmpegOutputError {
            get {
                return ResourceManager.GetString("FFmpegOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFprobe error: {0}..
        /// </summary>
        internal static string FFprobeError {
            get {
                return ResourceManager.GetString("FFprobeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFprobe not found. Make sure FFprobe is installed and in PATH..
        /// </summary>
        internal static string FFprobeNotFound {
            get {
                return ResourceManager.GetString("FFprobeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file &quot;{0}&quot; already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A file content disposition not found..
        /// </summary>
        internal static string FileContentDispositionNotFound {
            get {
                return ResourceManager.GetString("FileContentDispositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A type implementing stream functionality is required..
        /// </summary>
        internal static string ImplTypeIsRequired {
            get {
                return ResourceManager.GetString("ImplTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type &quot;{0}&quot; for stream &quot;{1}&quot; does not inherit the IStream..
        /// </summary>
        internal static string InadequateStreamType {
            get {
                return ResourceManager.GetString("InadequateStreamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid stream Id: &quot;{0}&quot;. It must be non-empty and URL-compatible..
        /// </summary>
        internal static string InvalidStreamId {
            get {
                return ResourceManager.GetString("InvalidStreamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metadata reading error for file: {0}. Reason: {1}.
        /// </summary>
        internal static string MetadataReadingError {
            get {
                return ResourceManager.GetString("MetadataReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing boundary in Content-Type..
        /// </summary>
        internal static string MissingBoundary {
            get {
                return ResourceManager.GetString("MissingBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expecting multipart form-data request..
        /// </summary>
        internal static string MultipartFormDataRequired {
            get {
                return ResourceManager.GetString("MultipartFormDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No files to play..
        /// </summary>
        internal static string NoFilesToPlay {
            get {
                return ResourceManager.GetString("NoFilesToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A path is required for file streams..
        /// </summary>
        internal static string PathIsRequired {
            get {
                return ResourceManager.GetString("PathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing track error on file {0}:
        ///{1}.
        /// </summary>
        internal static string PreparingTrackError {
            get {
                return ResourceManager.GetString("PreparingTrackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A stream registraton date-time is required..
        /// </summary>
        internal static string RegisteredIsRequired {
            get {
                return ResourceManager.GetString("RegisteredIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The SHOUTcast server returned a protocol error: {0}.
        /// </summary>
        internal static string ShoutCastProtocolError {
            get {
                return ResourceManager.GetString("ShoutCastProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The maximum length of a stream country is 100 characters..
        /// </summary>
        internal static string StreamCountryLengthExceeded {
            get {
                return ResourceManager.GetString("StreamCountryLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stream does not support uploading..
        /// </summary>
        internal static string StreamDoesntSupportUploading {
            get {
                return ResourceManager.GetString("StreamDoesntSupportUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A stream ID is required..
        /// </summary>
        internal static string StreamIdIsRequired {
            get {
                return ResourceManager.GetString("StreamIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The maximum length of a stream ID is 50 characters..
        /// </summary>
        internal static string StreamIdLengthExceeded {
            get {
                return ResourceManager.GetString("StreamIdLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The maximum length of a stream Tg-channel ID is 50 characters..
        /// </summary>
        internal static string StreamTgChannelLengthExceeded {
            get {
                return ResourceManager.GetString("StreamTgChannelLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A stream title is required..
        /// </summary>
        internal static string StreamTitleIsRequired {
            get {
                return ResourceManager.GetString("StreamTitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The maximum length of a stream title is 255 characters..
        /// </summary>
        internal static string StreamTitleLengthExceeded {
            get {
                return ResourceManager.GetString("StreamTitleLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The maximum length of a stream type is 150 characters..
        /// </summary>
        internal static string StreamTypeLengthExceeded {
            get {
                return ResourceManager.GetString("StreamTypeLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stream is unavailable..
        /// </summary>
        internal static string StreamUnavailable {
            get {
                return ResourceManager.GetString("StreamUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telegram message delete error: {0}.
        /// </summary>
        internal static string TelegramMessageDeleteError {
            get {
                return ResourceManager.GetString("TelegramMessageDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telegram message sending error: {0}.
        /// </summary>
        internal static string TelegramMessageSendError {
            get {
                return ResourceManager.GetString("TelegramMessageSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telegram sending file error: {0}.
        /// </summary>
        internal static string TelegramSendingFileError {
            get {
                return ResourceManager.GetString("TelegramSendingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The telegram service initializing error: {0}.
        /// </summary>
        internal static string TelegramServiceInitializingError {
            get {
                return ResourceManager.GetString("TelegramServiceInitializingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telegram webhook setting error: {0}.
        /// </summary>
        internal static string TelegramWebhookSettingError {
            get {
                return ResourceManager.GetString("TelegramWebhookSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete temp files: {0}.
        /// </summary>
        internal static string TempFilesDeleteError {
            get {
                return ResourceManager.GetString("TempFilesDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable define codec.
        /// </summary>
        internal static string UnableDefineCodec {
            get {
                return ResourceManager.GetString("UnableDefineCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable define sample rate.
        /// </summary>
        internal static string UnableDefineSampleRate {
            get {
                return ResourceManager.GetString("UnableDefineSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable define frame size.
        /// </summary>
        internal static string UnableDefineSamplesPerFrame {
            get {
                return ResourceManager.GetString("UnableDefineSamplesPerFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to read the uploaded file name..
        /// </summary>
        internal static string UnableReadUploadedFileName {
            get {
                return ResourceManager.GetString("UnableReadUploadedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File has an invalid extension. Only .mp3 or .acc is allowed..
        /// </summary>
        internal static string UnacceptableFileExtension {
            get {
                return ResourceManager.GetString("UnacceptableFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown stream..
        /// </summary>
        internal static string UnknownStreamId {
            get {
                return ResourceManager.GetString("UnknownStreamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown stream type &quot;{0}&quot; for id &quot;{1}&quot;..
        /// </summary>
        internal static string UnknownStreamType {
            get {
                return ResourceManager.GetString("UnknownStreamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URI is required for relay streams..
        /// </summary>
        internal static string UriIsRequired {
            get {
                return ResourceManager.GetString("UriIsRequired", resourceCulture);
            }
        }
    }
}
